### ISSUE TITLE
Optimizing gate voltage for Q1

### ISSUE THREAD

**Issue by franky1969** [bwack/C64-Saver-bwack#25] opened 2020-11-12 11:31 UTC
I have built the Saver 2.4 Throughole but the output voltage was  not disconnected at overvoltage. 
I meassured the output voltage of U1 (TL431) at overvoltage with 1,8V. The gate voltage of Q1 (2N7000) was after the divider 33k/82k at about 1.3V.
According to the Datasheet of the 2N7000 the Gate-Threshold Voltage of  is between 0.8 an 3V
I did not find the the max output voltage of U1 (TL431) in the datasheet. I think this is about 2V. 
I think the values of the divider resistors should be changed. I changed the 82k to a 33k resistor this works with my parts.
Maybe further investigation is necessary.

**Comment by bwack** [comment] 2020-11-14 10:17
Thanks a lot for letting me know! I think I'll change the 2n7000 to 2n7002 due to the wide spread Vgs threshold.

**Comment by franky1969** [comment] 2020-11-14 10:51
According from the Datasheet from National Semi the 2N7000 is a pin version and the 2N7002 the SMD version.
The threshold Voltages are nearly the same:
2N7000 : 0.8V - 3V 
207002 : 1V - 2.5V
The min. Voltage maybe the reason why there are less problems witch the SMD Version.

**Comment by bwack** [comment] 2020-11-14 11:28
You are right. The problem is also with the smd version.
I think if I can't find another nmos, I can go with an npn bipolar transistor. The resistors are there anyway, so it would be a job to ensure Vth, I_b, hFE and I_KA of the tl431 (which is plenty anyway).

**Comment by bwack** [comment] 2020-11-14 11:30
V2.5 for reference:
![Screenshot from 2019-12-20 14-04-55](https://user-images.githubusercontent.com/11380333/99146102-35c40500-2675-11eb-85ec-e0975a990e4e.png)

**Comment by franky1969** [comment] 2020-11-14 15:26
The Voltage divider i have chosen has an factor of 0.5 with R7/R8. So we can get 1V this is at least on the min. threshold of the MOSFET but in worst case we need 6V (threshold max. 3V) to switch the MOSFET.
So the divider is no save solution for the MOSFET but witch an bipolar transistor it should work. 

I think, i have another possible solution for the SMD Version. In the Wikipedia artikel about the TL431 i found this:

"On-state VCA drops to around 2 V, which is compatible with Transistor–transistor logic {TTL) and CMOS logic gates with 5 V power supply.[40] Low-voltage CMOS (e.g. 3.3 V or 1.8 V logic) requires level conversion with a resistive voltage divider,[40] or replacing the TL431 with a low-voltage alternative like the **TLV431**.[41]"

**Comment by bwack** [comment] 2020-11-24 23:18
Very interesting. I looked it up. One reason for choosing TL431 is the high V_KA absolute max ~40V ish, while tlv is 10V. It would need some clamping i guess. I think maybe a bipolar is fine.

**Comment by macacob** [comment] 2022-05-02 01:33
I recognize this is an old post but I am experiencing the same issue. I tested up to 7V and output voltage was not disconnected.  I'm going to try replacing the 82k resistor with a 33k as suggested by frankly1969.  I have rechecked my work and everything seems correct (correct components, good solder joints etc).  Any other suggestions?

Thanks very much for your work on this by the way. Really a great project that should help keep more C64s alive for years to come.

**Comment by bwack** [comment] 2023-03-19 01:44
Has anyone looked at this problem? In short, the challenge is that the "output" of U1 does not go to 0 V, it goes to around 2V and varies with device to device. Then there is the threshold level of 2n7002, which have worked for me, but because of tolerances it may not work for another board. Suggestions welcome. I might have a closer look myself. 
The pandemics and chip shortages amongst other events killed this project for me. I see some people building it over at forum64, and this might kickstart some interest to continue (or not).

**Comment by bwack** [comment] 2023-03-19 12:45
I've been simulating a tl431 with cathode voltages from 1V to 2V. With a bipolar npn transistor, the threshold is a lot more stable in the bipolar transistor than the nmos transistors. Also, not much change is needed to the layout (if any? I presume some pin re-arrangement). The R7 and R8 can be set to 330k and 100k.

**Comment by franky1969** [comment] 2023-03-19 15:07
Hi bwack,
do you still have the 2V problem with die bipolar solution? Maybe this is the red LED in the V2.5 Version. If there is no load connected to output, you get about 2V from the LED current trough R9/R10.

**Comment by bwack** [comment] 2023-03-19 16:56
Hi again. This problem is with the threshold of 2n222 and variation in tl431. Regarding the led problem we can have a look at that in another issue :)

**Comment by bwack** [comment] 2023-03-19 17:28
maybe i misunderstood. im playing with lt spice now. I'd like to take out the leds until i figure out the problem with tl431 and 2n2222.

**Comment by franky1969** [comment] 2023-03-19 18:15
Sorry, i miss understood your post about the output of 2V from U1. Forget my posting about the LED it has nothing to do with this topic.

**Comment by bwack** [comment] 2023-03-19 18:53
No problem. I'm simulating with a npn transistor now and it can work. A bc547 seemed to work fine..

**Comment by bwack** [comment] 2023-03-20 00:38
This is what I've come up for the new throughhole version.

![Screenshot_2023-03-20_01-31-20](https://user-images.githubusercontent.com/11380333/226220520-b0df4762-3305-484e-9ee4-f48a8a96940f.png)

Two leds, powered by the active components (D1, Q1). Removed zener at Q1. Rotated the two TO92 packages to block less of the ground fill. Believe it or not I managed to get all components on the pcb and route them. not pretty but functional i hope.

![Screenshot_2023-03-20_01-37-04](https://user-images.githubusercontent.com/11380333/226221163-abea9ed9-e6a6-4b78-aed7-e064e03d326e.png)
![Screenshot_2023-03-20_01-35-37](https://user-images.githubusercontent.com/11380333/226221164-a66ae992-3e2b-40dc-94e2-02dc3d804a0e.png)

**Comment by franky1969** [comment] 2023-03-20 06:27
Looks very nice. I have put this in my ltspice, which i found from two years ago. The BC547 is switching at about 2.5V. So this should work fine.

**Comment by bwack** [comment] 2023-05-20 15:47
I'm testing now and it seems to work, however I cannot test for parameter spread thouhg. I noticed that the V_DS was high. I'll make another issue about it.

**Comment by bwack** [comment] 2023-07-18 11:05
I'm closing this issue as resolved.

**Closed by bwack** 2023-07-18 11:05 UTC
